import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import { raleway, roboto_flex } from "@/utils/fonts";

const inter = Inter({ subsets: ["latin"] });
const ibm_plex_sans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: "100",
  variable: "--font-ibm-plex-sans",
});
export const metadata: Metadata = {
  title: "Better Call Saul",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${roboto_flex} ${raleway} ${ibm_plex_sans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
