import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { raleway, roboto_flex } from "@/utils/fonts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Better Call Saul",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${roboto_flex} ${raleway}`}>
        {children}
      </body>
    </html>
  );
}
